Homework 10
Leonteviu/infra pull request #6
Opened 2017-09-20 13:36 UTC by Leonteviu

2017-09-20 17:09 UTC, Artemmkin commented on README.md
> +- Создали директорию terraform в репозитории infra.
не думаю, что будет кому-то интересно читать, в какой последовательности писались конфиги. На мой пользовательский взгляд, было бы уместнее составить оставить только те части, которые описывают структуру репозитория и как начать с ним работать.

2017-09-20 17:15 UTC, Artemmkin requested changes
Привет! Выглядит все ок 👍 
Есть только замечания по структуре репозитория:
1.  Не нужно создавать новые шаблоны пакера, тем более в директории `ansible`. Шаблоны использоваться старые, что лежать в директории `packer`, но провижинер должен быть `ansible`. 
2. Переменные для пакера не должны храниться в директории `ansible`. И если хочешь оставить пример переменных, то я бы добавлял бы `.example` в конец названия файла, например, `variables.json.example`. 
3. Пожалуйста, переименуй созданные плейбуки  `reddit_app.yml` и `reddit_db.yml` в `packer_reddit_app.yml` и `packer_reddit_db.yml`

2017-09-20 17:16 UTC, Artemmkin commented
Как поправишь - отпиши здесь в комментах, чтобы я мог проверить

2017-09-22 12:49 UTC, Artemmkin approved these changes
Выглядит ок 👍 Пинай, когда проверка задерживается

2017-09-22 12:52 UTC, Leonteviu commented
Артем, я поправил. Посмотри, пожалуйста

2017-09-22 12:57 UTC, merged

2017-09-22 13:22 UTC, Artemmkin commented
Да, все норм, уже ведь одобрил